# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_table:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.retriever.table_list

simple_dpr_table:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.retriever.table_simple_list

mine_dpr_table:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.retriever.table_mine_list